apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: <%=name%>
subjects:
- kind: ServiceAccount
  name: <%=service_account_name%> # Name is case sensitive
  namespace: sso-dev
roleRef:
  kind: ClusterRole 
  name: <%=role%> 