apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: sso-bot
    application: <%=name%>
  labels:
    build: <%=name%>
    application: <%=name%>
  name: <%=name%>
spec:
  lookupPolicy:
    local: false
