apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  name: sso-bot
  namespace: sso-dev
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods", "services", "deploymentconfigs", "routes", "imagestreams", "secrets", "buildconfigs", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]